"""CLI for auto_coding v0.2 — Agentic coding system."""

from __future__ import annotations

from pathlib import Path

import typer
import shutil

app = typer.Typer(name="auto_coding", help="Agentic coding system v0.2")

# ── Phase 1 commands ──────────────────────────────────────

@app.command("init-from-codebook")
def init_from_codebook_cli(
    project_dir: str = typer.Option(..., help="Project output directory"),
    initial_codebook: str = typer.Option(..., help="Path to initial_codebook.md"),
    unit_table: str = typer.Option(..., help="Path to unit_table.csv"),
    config: str = typer.Option(None, help="Path to project_config.yaml"),
):
    """Initialize project directory from input files. Pilot sample is now auto-generated by sample-pilot."""
    from .io_utils import ensure_dir
    proj = ensure_dir(project_dir)
    inputs_dir = ensure_dir(proj / "00_inputs")
    for src, dst in [(initial_codebook, "initial_codebook.md"),
                     (unit_table, "unit_table.csv")]:
        if Path(src).exists():
            shutil.copy2(src, inputs_dir / dst)
    if config and Path(config).exists():
        shutil.copy2(config, inputs_dir / "project_config.yaml")
    for sub in ["01_codebook", "02_prompts", "03_units", "04_pilot", "03_training"]:
        ensure_dir(proj / sub)
    print(f"Project initialized: {proj}")


@app.command("standardize-codebook")
def standardize_codebook_cli(project_dir: str = typer.Option(..., help="Project directory")):
    from .codebook_standardizer import standardize
    r = standardize(Path(project_dir)/"00_inputs"/"initial_codebook.md",
                    Path(project_dir)/"01_codebook")
    print(f"Standardized {r['code_count']} codes → {r['yaml_path']}")


@app.command("review-codebook")
def review_codebook_cli(project_dir: str = typer.Option(..., help="Project directory")):
    from .codebook_review import review
    r = review(Path(project_dir)/"01_codebook"/"codebook_v0.1.yaml",
               Path(project_dir)/"01_codebook")
    print(f"Reviewed {r['total_codes']} codes, proceed={r['can_proceed']}")


@app.command("render-prompt")
def render_prompt_cli(project_dir: str = typer.Option(..., help="Project directory"),
                      codebook_version: str = typer.Option("v0.1"),
                      force: bool = typer.Option(False, help="Skip review gate check")):
    from .prompt_renderer import render
    import json
    # Gate check: read review result
    if not force:
        missing_path = Path(project_dir) / "01_codebook" / "codebook_missing_fields.json"
        if missing_path.exists():
            review = json.loads(missing_path.read_text(encoding="utf-8"))
            if not review.get("can_proceed_to_training", True):
                print("BLOCKED: codebook review failed (definition missing). Use --force to bypass.")
                raise typer.Exit(1)
    r = render(Path(project_dir)/"01_codebook"/f"codebook_{codebook_version}.yaml",
               Path(project_dir)/"02_prompts", expected_version=codebook_version)
    print(f"Rendered prompt → {r['prompt_path']}")


@app.command("validate-units")
def validate_units_cli(project_dir: str = typer.Option(..., help="Project directory")):
    from .unit_table_validator import validate
    r = validate(Path(project_dir)/"00_inputs"/"unit_table.csv",
                 Path(project_dir)/"03_units")
    print(f"Validated {r['total_units']} units, {r['issues_count']} issues")


@app.command("sample-pilot")
def sample_pilot_cli(
    project_dir: str = typer.Option(..., help="Project directory"),
    target_size: int = typer.Option(300, help="Target sample size"),
    seed: int = typer.Option(42, help="Random seed"),
    risk_config: str = typer.Option(None, help="风险画像 YAML（仅适用于 round_02 及以后）。Round 1 传入会打印警告"),
    control_group: str = typer.Option(None, help="需要在 pilot 中超采样的对照 group_id"),
):
    """Generate pilot sample. Round 1 uses only structural fields; Round 2+ can use risk profile."""
    from .pilot_sampler import sample
    rc = Path(risk_config) if risk_config else None
    if rc and not rc.exists():
        print(f"WARNING: risk-config file not found: {rc}, proceeding without it.")
        rc = None
    r = sample(
        Path(project_dir)/"03_units"/"unit_table_v0.1.csv",
        Path(project_dir)/"04_pilot",
        target_size=target_size,
        seed=seed,
        risk_config_path=rc,
        control_group=control_group,
    )
    print(f"Sampled {r['sampled_count']} units, groups={r['groups_covered']}, "
          f"risk_config={'YES' if r['risk_config_used'] else 'NO'}")


@app.command("build-risk-profile")
def build_risk_profile_cli(
    project_dir: str = typer.Option(..., help="Project directory"),
    source_round_id: str = typer.Option("round_01", help="来源轮次"),
    target_round_id: str = typer.Option("round_02", help="目标轮次"),
    min_confusion_count: int = typer.Option(2, help="最低混淆次数阈值"),
):
    """Generate risk_config candidate from round_N real disagreement/adjudication outputs."""
    from .risk_profile_builder import build_risk_config
    r = build_risk_config(project_dir, source_round_id, target_round_id, min_confusion_count)
    print(f"Risk profile: {r['explicit_units_count']} explicit units, "
          f"{r['confusion_pairs_count']} confusion pairs, "
          f"{r['boundary_patterns_count']} boundary patterns → {r['output_path']}")


@app.command("review-pilot-sample")
def review_pilot_sample_cli(project_dir: str = typer.Option(..., help="Project directory")):
    from .pilot_sample_review import review
    r = review(Path(project_dir)/"04_pilot"/"pilot_sample_units.csv",
               Path(project_dir)/"03_units"/"unit_table_v0.1.csv",
               Path(project_dir)/"04_pilot")
    print(f"Pilot: {r['pilot_n']}/{r['total_units']} ({r['pilot_pct']}), groups={r['groups_covered']}")


# ── Phase 2 command ───────────────────────────────────────

@app.command("train-coders")
def train_coders_cli(
    project_dir: str = typer.Option(..., help="Project directory"),
    codebook_version: str = typer.Option("v0.1"),
    round_id: str = typer.Option("round01"),
    mode: str = typer.Option("mock"),
    max_items: int = typer.Option(30),
):
    """Run coder training phase (mock/rule-based)."""
    from .coder_training import CoderTrainingAgent

    agent = CoderTrainingAgent(mode=mode, max_items=max_items)
    result = agent.run(
        project_dir=project_dir,
        codebook_version=codebook_version,
        round_id=round_id,
        max_items=max_items,
    )
    print(f"Training complete: {result['training_samples']} samples, "
          f"{result['issues']} issues, {result['suggestions']} suggestions, "
          f"candidate={'YES' if result['candidate_generated'] else 'NO'}")


# ── Phase 3 commands ───────────────────────────────────────

@app.command("pilot-code")
def pilot_code_cli(
    project_dir: str = typer.Option(..., help="Project directory"),
    round_id: str = typer.Option("round_01"),
    codebook_version: str = typer.Option("v0.2_candidate"),
    mode: str = typer.Option("mock"),
):
    """Run independent pilot coding (Coder A + Coder B)."""
    from .coder import run_pilot_coding
    result = run_pilot_coding(
        project_dir=project_dir, round_id=round_id,
        codebook_version=codebook_version, mode=mode,
    )
    print(f"Coder A: {result['coder_a_ok']}/{result['coder_a_count']} OK")
    print(f"Coder B: {result['coder_b_ok']}/{result['coder_b_count']} OK")
    print(f"Output: {result['round_dir']}")


@app.command("compute-reliability")
def compute_reliability_cli(
    project_dir: str = typer.Option(..., help="Project directory"),
    round_id: str = typer.Option("round_01"),
):
    """Compute reliability metrics between Coder A and Coder B."""
    from .reliability import compute_reliability
    metrics = compute_reliability(project_dir=project_dir, round_id=round_id)
    print(f"Kappa: {metrics['cohen_kappa']:.4f}, "
          f"Agreement: {metrics['percent_agreement']:.4f}, "
          f"Alpha: {metrics['krippendorff_alpha']:.4f}")


# ── Phase 4 commands ───────────────────────────────────────

@app.command("analyze-disagreements")
def analyze_disagreements_cli(
    project_dir: str = typer.Option(..., help="Project directory"),
    round_id: str = typer.Option("round_01"),
):
    """Identify and classify A/B disagreements."""
    from .disagreement_analysis import analyze
    r = analyze(project_dir=project_dir, round_id=round_id)
    print(f"Label disagreements: {r['label_disagreement_count']}/{r['valid_pairs']}")
    print(f"Review candidates: {r['review_candidate_count']}")
    print(f"Adjudication needed: {r['adjudication_count']}")
    print(f"Agreement: {r['agreement_count']}/{r['valid_pairs']} ({r['computed_percent_agreement']:.4f})")
    print(f"Consistency check: {'PASS' if r['consistency_check_passed'] else 'FAIL'}")


@app.command("adjudicate")
def adjudicate_cli(
    project_dir: str = typer.Option(..., help="Project directory"),
    round_id: str = typer.Option("round_01"),
    codebook_version: str = typer.Option("v0.2_candidate"),
    mode: str = typer.Option("mock"),
):
    """Adjudicate disagreements + generate decision log + consensus labels."""
    from .adjudicator import adjudicate
    from .decision_log import generate
    from .consensus_builder import build

    adj = adjudicate(project_dir, round_id, codebook_version)
    dlog = generate(project_dir, round_id)
    con = build(project_dir, round_id)
    print(f"Adjudicated: {adj['total']} (resolved={adj['resolved']}, unresolved={adj['unresolved']})")
    print(f"Decision log: {dlog['decisions']} entries")
    print(f"Consensus: {con['total']} (agreement={con['agreement']}, adjudication={con['adjudication']}, unresolved={con['unresolved']})")


# ── Phase 5 commands ───────────────────────────────────────

@app.command("refine-codebook")
def refine_codebook_cli(
    project_dir: str = typer.Option(..., help="Project directory"),
    round_id: str = typer.Option("round_01"),
    source_codebook_version: str = typer.Option("v0.2_candidate"),
    target_codebook_version: str = typer.Option("v0.3_candidate"),
    mode: str = typer.Option("mock"),
):
    """Generate codebook revision proposal and candidate."""
    from .codebook_refiner import refine
    r = refine(project_dir, round_id, source_codebook_version, target_codebook_version, mode)
    print(f"Changes: {r['changes_count']}, Proposal: {r['proposal_path']}")


@app.command("plan-recoding")
def plan_recoding_cli(
    project_dir: str = typer.Option(..., help="Project directory"),
    round_id: str = typer.Option("round_01"),
):
    """Generate recoding plan for next round."""
    from .recoding_planner import plan
    r = plan(project_dir, round_id)
    print(f"Requires recoding: {r['requires_recoding']}, Affected: {len(r['affected_unit_ids'])} units")


@app.command("decide-round")
def decide_round_cli(
    project_dir: str = typer.Option(..., help="Project directory"),
    round_id: str = typer.Option("round_01"),
    kappa_threshold: float = typer.Option(0.75),
    max_pilot_rounds: int = typer.Option(5),
):
    """Decide whether to freeze, continue, or stop."""
    from .round_controller import decide
    r = decide(project_dir, round_id, kappa_threshold, max_pilot_rounds)
    print(f"Decision: {r['decision']} → {r['next_action']}")
    print(f"Reason: {r['reason']}")


# ── Phase 6 commands ───────────────────────────────────────

@app.command("self-loop-round")
def self_loop_round_cli(
    project_dir: str = typer.Option(..., help="Project directory"),
    round_id: str = typer.Option("round_01"),
    codebook_version: str = typer.Option("v0.2_candidate"),
    mode: str = typer.Option("mock"),
    kappa_threshold: float = typer.Option(0.75),
):
    """Run a single pilot round: code → reliability → diagnosis → decision."""
    from .self_loop_runner import SelfLoopRunner
    runner = SelfLoopRunner(project_dir, mode=mode, kappa_threshold=kappa_threshold)
    r = runner.run_round(round_id=round_id, codebook_version=codebook_version)
    print(f"Round {r['round_id']}: Kappa={r['kappa']:.4f}, Decision={r['decision']} → {r['next_action']}")


@app.command("self-loop")
def self_loop_cli(
    project_dir: str = typer.Option(..., help="Project directory"),
    start_round_id: str = typer.Option("round_01"),
    initial_codebook_version: str = typer.Option("v0.2_candidate"),
    max_rounds: int = typer.Option(5),
    kappa_threshold: float = typer.Option(0.75),
    mode: str = typer.Option("mock"),
):
    """Auto-loop pilot rounds until stop condition."""
    from .self_loop_runner import SelfLoopRunner
    runner = SelfLoopRunner(project_dir, mode=mode, kappa_threshold=kappa_threshold,
                            max_rounds=max_rounds)
    state = runner.run_loop(start_round_id=start_round_id,
                            initial_codebook_version=initial_codebook_version)
    print(f"Rounds: {state['rounds_completed']}")
    print(f"Stopped: {state['stopped']} — {state['stop_reason']}")


# ── Phase 7 commands ───────────────────────────────────────

@app.command("freeze-codebook")
def freeze_codebook_cli(
    project_dir: str = typer.Option(..., help="Project directory"),
    force_freeze: bool = typer.Option(False, help="Force freeze even if gate blocked"),
):
    """Freeze codebook as v1.0 (requires gate check)."""
    from .codebook_freezer import freeze
    r = freeze(project_dir, force=force_freeze)
    if r["freeze_allowed"]:
        print(f"Frozen: v1.0 (source={r.get('source_version')}, forced={r.get('forced', False)})")
    else:
        print(f"BLOCKED: {r['reason']}")
        raise typer.Exit(1)


@app.command("formal-code")
def formal_code_cli(
    project_dir: str = typer.Option(..., help="Project directory"),
    mode: str = typer.Option("mock"),
):
    """Run formal double coding on all units."""
    from .formal_coding_manager import run_formal
    r = run_formal(project_dir, mode)
    print(f"Formal coding: A={r['coder_a_ok']}/{r['coder_a_total']}, B={r['coder_b_ok']}/{r['coder_b_total']}")


@app.command("formal-reliability")
def formal_reliability_cli(
    project_dir: str = typer.Option(..., help="Project directory"),
):
    """Compute formal reliability from formal A/B results."""
    from .reliability import compute_reliability
    import shutil, json
    fd = Path(project_dir) / "06_formal_coding"
    # Symlink-style: copy formal results to a temp round for reliability
    rd = Path(project_dir) / "04_pilot" / "formal_temp"
    rd.mkdir(parents=True, exist_ok=True)
    shutil.copy2(fd / "coder_A_formal.jsonl", rd / "coder_A_results.jsonl")
    shutil.copy2(fd / "coder_B_formal.jsonl", rd / "coder_B_results.jsonl")
    m = compute_reliability(str(Path(project_dir)), round_id="formal_temp")
    shutil.copy2(rd / "agreement_metrics.json", fd / "formal_agreement_metrics.json")
    shutil.copy2(rd / "code_level_metrics.json", fd / "formal_code_level_metrics.json")
    shutil.copy2(rd / "confusion_matrix.csv", fd / "formal_confusion_matrix.csv")
    shutil.copy2(rd / "reliability_report.md", fd / "formal_reliability_report.md")
    shutil.rmtree(rd)
    print(f"Formal Kappa: {m['cohen_kappa']:.4f}, Agreement: {m['percent_agreement']:.4f}")


@app.command("final-consensus")
def final_consensus_cli(
    project_dir: str = typer.Option(..., help="Project directory"),
):
    """Build final consensus from formal A/B results."""
    from .final_consensus import build_final_consensus
    r = build_final_consensus(project_dir)
    print(f"Consensus: {r['total']} (agreement={r['agreement']}, adjudication={r['adjudication']}, unresolved={r['unresolved']})")


@app.command("build-final-dataset")
def build_final_dataset_cli(
    project_dir: str = typer.Option(..., help="Project directory"),
):
    """Build final coding table from consensus labels."""
    from .final_dataset_builder import build
    r = build(project_dir)
    print(f"Final dataset: {r['total']} rows, {r['unresolved']} unresolved")


@app.command("archive-project")
def archive_project_cli(
    project_dir: str = typer.Option(..., help="Project directory"),
):
    """Generate archive manifest for the project."""
    from .archive_manager import archive
    r = archive(project_dir)
    print(f"Archive manifest: {r['file_count']} files")


# ── Acceptance Audit ──────────────────────────────────────

@app.command("acceptance-audit")
def acceptance_audit_cli(
    project_dir: str = typer.Option(..., help="Project directory"),
):
    """Run v1.0 final acceptance audit."""
    from .acceptance_auditor import audit
    r = audit(project_dir)
    passed = sum(1 for c in r["checks"] if c["passed"])
    print(f"Status: {r['status']} — {passed}/{len(r['checks'])} checks passed")
    if r["status"] == "ACCEPTED_WITH_NOTES":
        print(f"Risks: {r['risks']}")


# ── v1.1 commands ─────────────────────────────────────────

@app.command("build-audit-sample")
def build_audit_sample_cli(
    project_dir: str = typer.Option(..., help="Project directory"),
    target_size: int = typer.Option(100, help="Target sample size"),
    seed: int = typer.Option(42, help="Random seed"),
):
    """Build stratified audit sample for human + DeepSeek validation."""
    from .audit_sample_builder import build_audit_sample
    from .deepseek_validation_report import generate_placeholder_report
    m = build_audit_sample(project_dir, target_size=target_size, seed=seed)
    r = generate_placeholder_report(project_dir)
    print(f"Audit sample: {m['actual_size']} units (target={m['target_size']})")
    print(f"Labels: {m['label_distribution']}")
    print(f"Disagreement: {m['disagreement_samples']}, Risk: {m['risk_samples']}")
    print(f"Template: {m['template_path']}")
    print(f"Validation status: {r['status']}")


@app.command("write-human-audit-instructions")
def write_human_audit_instructions_cli(
    project_dir: str = typer.Option(..., help="Project directory"),
):
    """Generate human_audit_instructions.md."""
    from .human_audit_validator import write_instructions
    p = write_instructions(project_dir)
    print(f"Instructions: {p}")


@app.command("validate-human-audit")
def validate_human_audit_cli(
    project_dir: str = typer.Option(..., help="Project directory"),
):
    """Validate human_audit_template.csv."""
    from .human_audit_validator import validate
    r = validate(project_dir)
    print(f"Status: {r['status']} (ready={r['ready_for_metrics']})")
    print(f"Labeled: {r['labeled_count']}, Uncertain: {r['uncertain_count']}, Missing: {r['missing_label_count']}")


@app.command("compute-validation-metrics")
def compute_validation_metrics_cli(
    project_dir: str = typer.Option(..., help="Project directory"),
):
    """Compute mock vs human validation metrics."""
    from .validation_metrics import compute
    r = compute(project_dir)
    if r.get("status") == "AWAITING_HUMAN_LABELS":
        print(f"Status: AWAITING_HUMAN_LABELS (labeled={r.get('labeled_count', 0)})")
    else:
        print(f"Mock vs Human: Agreement={r['mock_vs_human_agreement']:.4f}, Kappa={r['mock_vs_human_kappa']:.4f}")


# ── v1.1 DeepSeek commands ─────────────────────────────────

@app.command("deepseek-pilot-code")
def deepseek_pilot_code_cli(
    project_dir: str = typer.Option(..., help="Project directory"),
    round_id: str = typer.Option("round_01"),
    codebook_version: str = typer.Option("v1.0"),
    mode: str = typer.Option("mock"),
    max_items: int = typer.Option(30),
):
    """Run DeepSeek A/B coding on pilot sample."""
    from .deepseek_coder import run_deepseek_coding
    r = run_deepseek_coding(project_dir, round_id, codebook_version, mode, max_items)
    print(f"DeepSeek coding: A={r['coder_a_ok']}/{r['coder_a_total']}, B={r['coder_b_ok']}/{r['coder_b_total']}")


@app.command("deepseek-adjudicate")
def deepseek_adjudicate_cli(
    project_dir: str = typer.Option(..., help="Project directory"),
    round_id: str = typer.Option("round_01"),
    codebook_version: str = typer.Option("v1.0"),
    mode: str = typer.Option("mock"),
):
    """Adjudicate DeepSeek disagreements."""
    from .deepseek_adjudicator import run_deepseek_adjudication
    r = run_deepseek_adjudication(project_dir, round_id, codebook_version, mode)
    print(f"Adjudicated: {r['total']} (resolved={r['resolved']}, unresolved={r['unresolved']})")


@app.command("deepseek-refine-codebook")
def deepseek_refine_codebook_cli(
    project_dir: str = typer.Option(..., help="Project directory"),
    round_id: str = typer.Option("round_01"),
    codebook_version: str = typer.Option("v1.0"),
    mode: str = typer.Option("mock"),
):
    """Generate DeepSeek codebook revision proposals."""
    from .deepseek_codebook_refiner import run_deepseek_refine
    r = run_deepseek_refine(project_dir, round_id, codebook_version, mode)
    print(f"Changes: {r['changes_count']}")


@app.command("deepseek-self-loop-round")
def deepseek_self_loop_round_cli(
    project_dir: str = typer.Option(..., help="Project directory"),
    round_id: str = typer.Option("round_01"),
    codebook_version: str = typer.Option("v1.0"),
    mode: str = typer.Option("mock"),
    max_items: int = typer.Option(30),
):
    """Run one round of DeepSeek self-loop: code → adjudicate → refine."""
    from .deepseek_coder import run_deepseek_coding
    from .deepseek_adjudicator import run_deepseek_adjudication
    from .deepseek_codebook_refiner import run_deepseek_refine
    print(f"[1/3] DeepSeek coding...")
    c = run_deepseek_coding(project_dir, round_id, codebook_version, mode, max_items)
    print(f"  A={c['coder_a_ok']}/{c['coder_a_total']}, B={c['coder_b_ok']}/{c['coder_b_total']}")
    print(f"[2/3] DeepSeek adjudication...")
    a = run_deepseek_adjudication(project_dir, round_id, codebook_version, mode)
    print(f"  Resolved={a['resolved']}, Unresolved={a['unresolved']}")
    print(f"[3/3] DeepSeek refine...")
    r = run_deepseek_refine(project_dir, round_id, codebook_version, mode)
    print(f"  Changes={r['changes_count']}")


@app.command("audit-deepseek-run")
def audit_deepseek_run_cli(
    project_dir: str = typer.Option(..., help="Project directory"),
    run_dir: str = typer.Option("09_deepseek_runs/round_01", help="DeepSeek run directory"),
):
    """Audit a DeepSeek run."""
    from .deepseek_run_auditor import audit
    r = audit(project_dir, run_dir)
    print(f"A: {r.get('coder_A_rows',0)} rows, {r.get('coder_A_parse_ok',0)} OK")
    print(f"B: {r.get('coder_B_rows',0)} rows, {r.get('coder_B_parse_ok',0)} OK")
    print(f"Agreement: {r.get('agreement_count','?')}/{r.get('agreement_pairs','?')} ({r.get('agreement_pct','?')})")
    print(f"API calls: {r.get('api_real_calls',0)}, Tokens: {r.get('api_tokens',0)}")


@app.command("deepseek-adjudication-stress-test")
def deepseek_stress_test_cli(
    project_dir: str = typer.Option(..., help="Project directory"),
    source_run_dir: str = typer.Option("09_deepseek_runs/round_01_30"),
    max_cases: int = typer.Option(5),
    mode: str = typer.Option("mock"),
):
    """Run stress test for adjudication/refiner pipeline."""
    from .deepseek_stress_test import run_stress_test
    r = run_stress_test(project_dir, source_run_dir, max_cases, mode)
    print(f"Stress test: {r['total']} cases, resolved={r['resolved']}")
    print("WARNING: Stress test results are artificially constructed. Do NOT use as real coding results.")


if __name__ == "__main__":
    app()
